on:
  push:
    branches:
    - main
    paths:
    - 'nicegui/**'
    - '.github/workflows/Container-deploy.yml'

env:
  workingDir: '${{ github.workspace }}/nicegui'
  imageName: 'niceguitest'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    # - name: Wait for Terraform Apply to succeed
    #   uses: lewagon/wait-on-check-action@v1.3.1
    #   with:
    #     ref: ${{ github.ref }}
    #     check-name: 'Terraform Apply'
    #     repo-token: ${{ secrets.GITHUB_TOKEN }}
    #     wait-interval: 10

    - uses: Azure/login@v1
      with:
        creds: '{
                  "clientId":"${{ secrets.AZURE_CLIENT_ID }}",
                  "clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}",
                  "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}",
                  "tenantId":"${{ secrets.AZURE_TENANT_ID }}"
                }'

    - uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: "NiceGuiTest-KV" # name of key vault in Azure portal
        secrets: 'aca-url, aca-user, aca-pass'  # comma separated list of secret keys to fetch from key vault 
      id: acaKeyVault # ID for secrets that you will reference

    # - uses: azure/docker-login@v1
    #   with:
    #     login-server: ${{ steps.acaKeyVault.outputs.ACR-URL }}
    #     username: ${{ steps.acaKeyVault.outputs.ACR-USER }}
    #     password: ${{ steps.acaKeyVault.outputs.ACR-PASS }}

    # - run: |
    #     docker build . -t ${{ steps.acaKeyVault.outputs.ACR-URL }}/${{ env.imageName }}:${{ github.sha }}
    #     docker push ${{ steps.acaKeyVault.outputs.ACR-URL }}/${{ env.imageName }}:${{ github.sha }}
    #   working-directory: ${{ env.workingDir }}

    - name: Build and deploy Container App
      uses: azure/container-apps-deploy-action@v0
      with:
        appSourcePath: ${{ env.workingDir }}
        acrName: NiceGuiTestACR
        resourceGroup: NiceGuiTest
        containerAppEnvironment: NiceGuiTest-ACE
        containerAppName: niceguitest-aca
        targetPort: 8080
        imageToBuild: ${{ steps.acaKeyVault.outputs.aca-url }}/${{ env.imageName }}:${{ github.sha }}
        acrUsername: ${{ steps.acaKeyVault.outputs.aca-user }}
        acrPassword: ${{ steps.acaKeyVault.outputs.aca-pass }}