on:
  push:
    branches:
    - main
    paths:
    - 'nicegui/**'
    - '.github/workflows/Python-lint.yml'
  workflow_dispatch:
  pull_request:
    branches:
    - '*'
    paths:
    - 'nicegui/**'
    - '.github/workflows/Python-lint.yml'

jobs:
  python-lint:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2

     - uses: marian-code/python-lint-annotate@v3
       with:
         python-root-list: "./nicegui"
         use-black: true
         use-isort: true
         use-mypy: true
         use-pycodestyle: true
         use-pydocstyle: true
         #extra-pycodestyle-options: "--max-line-length=88"
         use-pylint: false
         use-flake8: false
         use-vulture: true
         python-version: "3.10"
